<?php

function load_courses()
{
    return null;
}

function load_teachers()
{
    return node_load_multiple([], ['type' => 'teachers']);
}

function load_price()
{
    $price = [
        [
            'title' => '编程试课',
            'price' => 0,
            'count' => 4,
            'des' => [
                '计算机文化基础',
                '网页编程',
//                'Scratch编程',
//                'Python编程',
//                'C语言编程',
            ]
        ],


        [
            'title' => '咏春拳试课',
            'price' => 0,
            'count' => 4,
            'des' => [
                '咏春拳原理',
                '咏春拳小念头与格斗技法',
            ]
        ],


        [

            'title' => '编程初级班',
            'price' => 2600,
            'count' => 24,
            'des' => [
                '计算机文化基础',
                '网页编程与Scratch编程任选一种',
            ]
        ],

        [

            'title' => '编程中级班',
            'price' => 3000,
            'count' => 28,
            'des' => [
                '计算机文化基础',
                '初级班任选一种深入学习',
            ],
        ],


        [

            'title' => '高级班-C语言编程',
            'price' => 4000,
            'count' => 46,
            'des' => [
                '计算机文化基础',
                'C语言编程实战，计算机二级考试',
            ],
        ],

        [

            'title' => '高级班-Python编程',
            'price' => 2500,
            'count' => 24,
            'des' => [
                '计算机文化基础',
                'Python编程实战',
            ],
        ],

    ];


    return array_chunk($price, 3);
}

function zmdg_node_load($nodes, $types)
{

    // Decide whether any of $types are relevant to our purposes.
    if (count(array_intersect(['courses', 'teachers', 'article'], $types))) {
        foreach ($nodes as $node) {
            if(isset($node->field_img))
            {
                $node->img = file_create_url($node->field_img['und'][0]['uri']);

            }

            else{
                $node->img = file_create_url($node->field_image['und'][0]['uri']);

            }
            $node->field_summery = $node->body['und'][0]['safe_summary'];
            $node->field_body = $node->body['und'][0]['safe_value'];
            $node->field_role = $node->field_role['und'][0]['safe_value'];
            $node->uri = url(node_uri($node)['path']);

        }
    }



}


function zmdg_node_view($node, $view_mode, $langcode)
{
    if($view_mode == 'full'){

    }

}




function zmdg_menu()
{
    $items['about'] = array(
        'title' => '关于',
        'page callback' => 'zmdg_about',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu'
    );


    $items['news'] = array(
        'title' => '动态',
        'page callback' => 'zmdg_news',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu'
    );



    return $items;
}


function zmdg_news()
{
    require_once drupal_get_path('module', 'taxonomy') . '/taxonomy.pages.inc';
    $term = taxonomy_term_load(1);
    $build = taxonomy_term_page($term);

    $build['term_heading']['#markup'] = '<div class="page-common-title">
<em>Latest News</em>
        <h3>翼橙新闻</h3>
        </div>';
    $build['#prefix'] = '<section class="news-page"><div class="news-list-box"><ul class="news-list clearfix">';
    $build['#suffix'] = '</ul></div></section>';

    return $build;
}


function zmdg_about()
{
    $build['about'] = ['#theme' => 'about'];
    $build['service'] = ['#theme' => 'service'];
    $build['team'] = ['#theme' => 'team', '#teachers' => load_teachers()];
    return $build;
}

function zmdg_theme()
{
    $path = drupal_get_path('module', 'zmdg');
    return [
        'courses' => [
            'variables' => ['description' => false],
            'path' => $path . '/tpl',
            'template' => 'courses',
        ],


        'help' => [
            'path' => $path . '/tpl',
            'template' => 'help',
        ],


        'team' => [
            'variables' => ['teachers' => null],
            'path' => $path . '/tpl/about',
            'template' => 'team',
        ],

        'service' => [
            'path' => $path . '/tpl/about',
            'template' => 'service',
        ],
        'about' => [
            'path' => $path . '/tpl/about',
            'template' => 'about',
        ],



    ];

}


function zmdg_is_teachers_page()
{
    if ($_GET['q'] == 'teachers') return true;
    return false;
}

function zmdg_is_courses_page()
{
    if ($_GET['q'] == 'courses') return true;
    return false;
}

function courses()
{

    $img = file_create_url('public://images/course.jpg');
    $build['top_image'] = ['#theme' => 'top_image', '#img' => $img];
    $build['courses'] = ['#theme' => 'courses', '#courses' => load_courses()];
    return $build;

}

function teachers()
{
    $img = file_create_url('public://images/teach.png');
    $build['top_image'] = ['#theme' => 'top_image', '#img' => $img];
    $build['teachers'] = ['#theme' => 'teachers', '#teachers' => array_chunk(load_teachers(), 4)];
    return $build;
}